FROM golang:latest AS build

WORKDIR /src
COPY . .
RUN make build_linux

FROM ubuntu:latest
COPY --from=build /src/_output/linux/yarr /usr/local/bin/yarr

RUN mkdir -p /data

ENV YARR_DB /data/yarr.db
ENV YARR_ADDR 0.0.0.0:7070
ENV YARR_AUTH "username:password"
ENV YARR_AUTHFILE ""
# Base URL for Yarr
ENV YARR_BASE ""
# /data/authfile
ENV YARR_CERTFILE ""
ENV YARR_KEYFILE ""
ENV YARR_LOGFILE ""

EXPOSE 7070

ENTRYPOINT ["/usr/local/bin/yarr"]
